Importing Libraries

In [ ]:
import numpy as np #Importing Numpy for Numerical Operations
import pandas as pd #Importing Pandas for Data visualization and Data Analysis
import tensorflow as tf #Importing TensorFlow function 

In [ ]:
tf.__version__

'2.8.2'

In [ ]:
dataset = pd.read_csv('Churn_Modelling.csv') # Reading dataset from Churn_modelling.csv; Containing 10000 rows and 14 columns 
x = dataset.iloc[:, 3:-1].values # Assigning 'x' data from churn modelling dataset as inputs; from the dataset all the rows and columns from 3 to 12 
y = dataset.iloc[:, -1].values # Last column of dataset is declared as 'y' for output

In [ ]:
print(x[:5, :]) # To display first 5 rows from 'x' data

[[619 'France' 'Female' 42 2 0.0 1 1 1 101348.88]
 [608 'Spain' 'Female' 41 1 83807.86 1 0 1 112542.58]
 [502 'France' 'Female' 42 8 159660.8 3 1 0 113931.57]
 [699 'France' 'Female' 39 1 0.0 2 0 0 93826.63]
 [850 'Spain' 'Female' 43 2 125510.82 1 1 1 79084.1]]


In [ ]:
print(x[:1, :]) # To display first row from 'x' data

[[619 'France' 'Female' 42 2 0.0 1 1 1 101348.88]]


In [ ]:
print(y) # Display 'y' data

[1 0 1 ... 1 1 0]


Encoding Categorical data

In [ ]:
from sklearn.preprocessing import LabelEncoder # Importing LabelEncoder from sklearn.preprocessing for Encode target labels with value between 0 and n_classes-1
le = LabelEncoder() # Declare 'le' variable for LabelEncoder() function
x[:, 2] = le.fit_transform(x[:, 2]) # This line encode the column 2 in 'x' data as target values 0 & 1 for gender difference. Male - 1; Female - 0

In [ ]:
print(x[:5, :]) # To display first 5 rows from 'x' data

[[619 'France' 0 42 2 0.0 1 1 1 101348.88]
 [608 'Spain' 0 41 1 83807.86 1 0 1 112542.58]
 [502 'France' 0 42 8 159660.8 3 1 0 113931.57]
 [699 'France' 0 39 1 0.0 2 0 0 93826.63]
 [850 'Spain' 0 43 2 125510.82 1 1 1 79084.1]]


In [ ]:
print(x[4:5, :]) # To display 5th row alone from 'x' data

[[850 'Spain' 0 43 2 125510.82 1 1 1 79084.1]]


Column Transformer Function
sciket-learn class used to create and apply separate transformers for numerical and categorical data.

In [ ]:
from sklearn.compose import ColumnTransformer # Importing ColumnTransformer function from sklearn library
from sklearn.preprocessing import OneHotEncoder #Import OneHotEncoder function for preprocessing from sklearn
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder = 'passthrough') # Transformer Name: encoder; OneHotEncoder constructor for 2nd column datas are transformed into estimator; Remainder:Without any changes pass the values.  
X = np.array(ct.fit_transform(x)) # To fit and transform the dataset to label encode and one hot encode the column

In [ ]:
print(X[:1,:]) # Display 1st row data after ColumnTransformer function done

[[1.0 0.0 0.0 619 0 42 2 0.0 1 1 1 101348.88]]


Data Augmentation and Preprocessing

In [ ]:
from sklearn.model_selection import train_test_split # # This function splitting the data as train and test with the help of sklearn.model_selection
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state = 0) ## Train_set = 80%; Test_set = 20%; Random_sample = 0

In [ ]:
from sklearn.preprocessing import StandardScaler #importing StandardScaler function from sklearn.preprocessing directory
sc = StandardScaler() # Declare variable 'sc' for the output of StandardScaler function
X_train = sc.fit_transform(x_train) # x_train standardscaler transformation has done and save the output in X_train variable
X_test = sc.transform(x_test) # x_test standardscaler transformation has done and save the output in X_test variable

Model Preparation and Evaluation

In [ ]:
ann = tf.keras.models.Sequential()  # A sequential model to pass various ANN layers
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) # ANN Layer1 with 6 neurons/ hidden layers and activation function used here is "ReLu" Rectified Linear Unit
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) # ANN Layer2 with 6 neurons/ hidden layers and activation function used here is "ReLu"
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid')) # Output layer with activation function as 'Sigmoid' for binary classification

Compile model

In [ ]:
ann.compile(optimizer = 'adam',loss= 'binary_crossentropy', metrics = ['accuracy']) # Compiling done with the 'adam'(Adaptable Optimizer); Loss = binary_crossentropy for binary classification and metrics measured in this is accuracy

In [ ]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100) # Evaluation metrics for training accuracy determination with batch_size of 32 and No. of epochs = 100

Epoch 1/100
250/250 [==============================] - 2s 2ms/step - loss: 0.5071 - accuracy: 0.7960
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4532 - accuracy: 0.7956
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4392 - accuracy: 0.7940
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4337 - accuracy: 0.7951
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4303 - accuracy: 0.7955
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4276 - accuracy: 0.7966
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4247 - accuracy: 0.7980
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4215 - accuracy: 0.8099
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4167 - accuracy: 0.8152
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4090 - accura

In [ ]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 60) # Evaluation metrics for training accuracy determination with batch_size of 32 and No. of epochs = 60

Epoch 1/60
250/250 [==============================] - 1s 3ms/step - loss: 0.3308 - accuracy: 0.8660
Epoch 2/60
250/250 [==============================] - 1s 3ms/step - loss: 0.3309 - accuracy: 0.8655
Epoch 3/60
250/250 [==============================] - 1s 3ms/step - loss: 0.3303 - accuracy: 0.8660
Epoch 4/60
250/250 [==============================] - 0s 2ms/step - loss: 0.3303 - accuracy: 0.8656
Epoch 5/60
250/250 [==============================] - 0s 2ms/step - loss: 0.3302 - accuracy: 0.8656
Epoch 6/60
250/250 [==============================] - 0s 2ms/step - loss: 0.3305 - accuracy: 0.8668
Epoch 7/60
250/250 [==============================] - 0s 2ms/step - loss: 0.3307 - accuracy: 0.8661
Epoch 8/60
250/250 [==============================] - 0s 2ms/step - loss: 0.3307 - accuracy: 0.8656
Epoch 9/60
250/250 [==============================] - 0s 2ms/step - loss: 0.3304 - accuracy: 0.8652
Epoch 10/60
250/250 [==============================] - 0s 2ms/step - loss: 0.3303 - accuracy: 0.8648

In [ ]:
ann.summary() # Display summary of model architecture

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (32, 6)                   78        
                                                                 
 dense_1 (Dense)             (32, 6)                   42        
                                                                 
 dense_2 (Dense)             (32, 1)                   7         
                                                                 
Total params: 127
Trainable params: 127
Non-trainable params: 0
_________________________________________________________________


In [ ]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))>0.5) # ANN prediction result as if "output>0.5" print 'False' else 'True' 

[[False]]


In [ ]:
y_pred = ann.predict(X_test) # ANN Prediction for x_test for test data 
y_pred = (y_pred > 0.5) # Fixing threshold condition as 0.5 to predict the result.
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)) # Concatenating the y_pred and y_test through reshape and printing the result

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score # Importing accuracy_score and confusion_matrix from sklearn.metrics
cm = confusion_matrix(y_test, y_pred), # Fetching y_test and y_pred data to determine confusion matrix
print(cm) # Display Confusion matrix result
accuracy_score(y_test, y_pred) # Evaluation of final accuracy score of the model

(array([[1495,  100],
       [ 187,  218]]),)


0.8565